# -*- coding: utf-8 -*-
"""Linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dDZ4Y_6RvmJsS9NjETQWf_2gbqYODOev
"""

#upload your file on google drive
# and then mount drive
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

#copy path of file in drive and paste it below
path="/content/drive/MyDrive/ML Projects/Houseprice.csv"
df=pd.read_csv(path)
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('Area(sqr ft)')
plt.ylabel('Price(US$)')
plt.scatter(df.area,df.price,color='red',marker='*')
plt.plot(df.area,reg.predict(df[['area']]),color="blue")

reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

#array = 3300
reg.predict([[3300]])

reg.coef_

reg.intercept_

# y=m*x+b  x->3300
135.78767123*3300 + 180616.43835616432

d= pd.read_csv("/content/drive/MyDrive/ML Projects/test_area.csv")
d.head(4)

p=reg.predict(d[['area']])
p

d['price']=p
d

#d.to_csv("prediction.csv",index=False)
# Save to Google Drive using the full path
#You will find a new file in drive at below path location
d.to_csv("/content/drive/MyDrive/ML Projects/prediciton.csv", index=False)